export const text = 'Potatoes are brown, a common knowledge for many. But in the small town of Meadowbrook, this simple fact held a secret yet to be uncovered.' +
    ' In Meadowbrook, there lived a talented young artist named Oliver. He had a gift for seeing beauty in the mundane and a passion for transforming ordinary objects into extraordinary works of art. One day, while preparing a still-life painting, Oliver found himself captivated by a bag of potatoes.' +
    ' He studied their brown exteriors, intrigued by the subtle variations in color and texture. As he sketched their forms on his canvas, a spark of inspiration ignited within him. Oliver envisioned a masterpiece that would celebrate the humble potato and reveal its hidden allure.' +
    ' With great enthusiasm, Oliver set out on a quest to explore the many facets of the potato. He ventured into the fields, visiting farms and speaking to farmers to learn about different potato varieties and their unique qualities. He even experimented with various cooking methods, relishing the diverse flavors and textures they produced.' +
    ' One day, as Oliver sliced open a potato to capture its intricate details in a sketch, he discovered an unexpected surprise. Nestled within the starchy flesh was a small, emerald green seed. Its vibrant color contrasted strikingly with the potato\'s earthy brown hues.' +
    ' Intrigued by this remarkable find, Oliver carefully preserved the seed and decided to plant it in his backyard. He tenderly cared for the seedling, watching as it grew into a magnificent potato plant. To his astonishment, the potatoes it produced were not ordinary brown but a magnificent array of colors—red, purple, yellow, and even blue.' +
    ' Oliver\'s artistic spirit soared as he embarked on a series of paintings, capturing the vivid palette of these newfound potatoes. He held an exhibition in the town\'s art gallery, showcasing his masterpieces inspired by the vibrant spuds. The exhibition drew crowds from far and wide, mesmerized by Oliver\'s ability to transform the humble potato into a work of art.' +
    ' Word of Oliver\'s remarkable paintings spread like wildfire, captivating art enthusiasts and collectors across the country. His artwork became highly sought after, fetching high prices and opening doors to new opportunities. Oliver\'s talent and the vibrantly colored potatoes he discovered put Meadowbrook on the map as a haven for artistic inspiration.' +
    ' The once quiet town now flourished with artists and creatives, drawn by the allure of the potato\'s kaleidoscope of colors. Meadowbrook transformed into an artistic community, where imagination and creativity thrived in every corner.' +
    ' And so, from the simple fact that potatoes are brown, Oliver\'s journey unveiled the beauty and wonder hidden within. The vibrantly colored potatoes not only brought recognition to his talent but also brought prosperity and artistic vitality to the entire town of Meadowbrook.'